"""AOT SM89 BF16 paged attention; checked ABI, scheduler tiles of 128 rows."""
import argparse
import importlib.metadata
import json
import re
from pathlib import Path
import cutlass
import cutlass.cute as cute
from cutlass.cute.runtime import make_ptr
import cuda.bindings.driver as cuda
from flash_attention2 import flash_attention2_bf16_b1_hq32_hkv8_d128_q64_kv64_bs1 as kernel

@cute.jit
def launch(
    q: cute.Pointer,
    k_pool: cute.Pointer,
    v_pool: cute.Pointer,
    output: cute.Pointer,
    block_tables: cute.Pointer,
    kv_lens: cute.Pointer,
    cu_q_lens: cute.Pointer,
    block2req: cute.Pointer,
    block2tile: cute.Pointer,
    valid_q_tiles: cute.Pointer,
    q_stride_seq: cutlass.Int64,
    q_stride_head: cutlass.Int64,
    o_stride_seq: cutlass.Int64,
    o_stride_head: cutlass.Int64,
    max_blocks_per_seq: cutlass.Int32,
    block_size: cutlass.Int32,
    total_q_tiles: cutlass.Int32,
    batch: cutlass.Int32,
    num_tokens: cutlass.Int32,
    head_num: cutlass.Int32,
    kv_head_num: cutlass.Int32,
    head_dim: cutlass.Int32,
    scale: cutlass.Float32,
    causal: cutlass.Boolean,
    stream: cuda.CUstream
):
    kernel(q, k_pool, v_pool, output, block_tables, kv_lens, cu_q_lens, block2req, block2tile, valid_q_tiles, q_stride_seq, q_stride_head, o_stride_seq, o_stride_head, max_blocks_per_seq, block_size, total_q_tiles, batch, num_tokens, head_num, kv_head_num, head_dim, scale, causal, stream, scheduler_q_tile=128).launch(
        grid=(total_q_tiles * 2, 32, 1), block=(128, 1, 1), stream=stream)

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--out-dir', type=Path, required=True)
    args = p.parse_args()
    assert importlib.metadata.version('nvidia-cutlass-dsl') == '4.7.1'
    ptr = lambda dtype: make_ptr(dtype, 0, cute.AddressSpace.gmem, assumed_align=16 if dtype == cutlass.BFloat16 else 4)
    arguments = ([ptr(cutlass.BFloat16) for _ in range(4)]
        + [ptr(cutlass.Uint32)] + [ptr(cutlass.Int32) for _ in range(5)]
        + [cutlass.Int64(x) for x in (6144, 128, 4096, 128)]
        + [cutlass.Int32(x) for x in (4096, 1, 32, 8, 4096, 32, 8, 128)]
        + [cutlass.Float32(128**-0.5), cutlass.Boolean(True), cuda.CUstream(0)])
    compiled = cute.compile(launch, *arguments, options='--gpu-arch=sm_89 --keep-ptx --keep-cubin')
    ptx = compiled.artifacts.PTX
    if not ptx.lstrip().startswith('//'): ptx = Path(ptx).read_text()
    entries = re.findall(r'\.visible\s+\.entry\s+(\w+)\s*\((.*?)\)', ptx, re.S)
    assert len(entries) == 1
    name, params = entries[0]
    types = re.findall(r'\.param\s+\.(\w+)', params)
    assert types == ['u64']*14 + ['u32']*8 + ['f32', 'u8', 'u64'], types
    assert re.search(r'\.reqntid\s+128,\s*1,\s*1', ptx)
    image = compiled.artifacts.CUBIN
    if isinstance(image, str): image = Path(image).read_bytes()
    assert isinstance(image, bytes) and image.startswith(b'\x7fELF')
    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir/'cute_attention_sm89.cubin').write_bytes(image)
    (args.out_dir/'cute_attention_sm89.ptx').write_text(ptx)
    header = '// Generated by compile_attention.py.\n#pragma once\n'
    header += 'alignas(16) static const unsigned char cute_attention_image[] = {\n'
    for offset in range(0,len(image),32):
        header += ','.join(str(b) for b in image[offset:offset+32])+',\n'
    header += '};\nstatic const char cute_attention_name[] = '+json.dumps(name)+';\n'
    (args.out_dir/'cute_attention_sm89.h').write_text(header)
    print('Compiled SM89 attention, scheduler Q128 -> two Q64 CTAs, 25-parameter ABI checked')

if __name__ == '__main__': main()
