#!/usr/bin/env python3
"""Compile pinned CuTe DSL RMSNorm to cubins with a checked Rust ABI manifest."""

import argparse
import importlib.metadata
import json
import os
import re
import sys
from pathlib import Path

CUTLASS_VERSION = "4.7.1"
BLOCKS = tuple(1 << power for power in range(5, 15))


def compile_kernels(arch: str, out_dir: Path) -> None:
    sys.dont_write_bytecode = True
    try:
        version = importlib.metadata.version("nvidia-cutlass-dsl")
    except importlib.metadata.PackageNotFoundError as exc:
        raise RuntimeError(
            f"Install nvidia-cutlass-dsl=={CUTLASS_VERSION} in {sys.executable} "
            "and set RUSTINFER_CUTE_DSL_PYTHON to that interpreter."
        ) from exc
    if version != CUTLASS_VERSION:
        raise RuntimeError(f"Expected nvidia-cutlass-dsl=={CUTLASS_VERSION}, found {version}")
    match = re.fullmatch(r"sm_([0-9]+)a?", arch)
    if match is None or int(match[1]) < 80:
        raise ValueError(f"CuTe DSL RMSNorm requires sm_80 or newer, got {arch!r}")
    sm = int(match[1])
    out_dir = out_dir.resolve()
    dump_dir = out_dir / "cute_dsl_artifacts"
    dump_dir.mkdir(parents=True, exist_ok=True)
    os.environ["CUTE_DSL_DUMP_DIR"] = str(dump_dir)
    os.environ["CUTE_DSL_NO_CACHE"] = "1"
    import cutlass
    import cutlass.cute as cute
    from cutlass.cute.runtime import make_ptr
    from rmsnorm import rmsnorm

    lines = [
        "// Generated by cute_dsl/compile.py; do not edit.",
        f"pub(crate) const TARGET_SM: i32 = {sm};",
        "pub(crate) static KERNELS: &[KernelSpec] = &[",
    ]
    for dtype_id, dtype in enumerate((cutlass.Float32, cutlass.Float16, cutlass.BFloat16)):
        # Compile with typed null pointers, never execute a Python kernel.
        # The dimension/epsilon are runtime scalars, not specializations.
        ptr = make_ptr(dtype, 0, cute.AddressSpace.gmem, assumed_align=dtype.width // 8)
        compiled = cute.compile(
            rmsnorm, ptr, ptr, ptr, cutlass.Int32(37), cutlass.Float32(1e-5),
            options=f"--gpu-arch={arch} --keep-ptx --keep-cubin",
        )
        ptx = compiled.artifacts.PTX
        if not isinstance(ptx, str):
            raise RuntimeError("CuTe DSL did not return PTX")
        if not ptx.lstrip().startswith("//"):
            ptx = Path(ptx).read_text()
        entries = re.findall(r"\.visible\s+\.entry\s+(\w+)\s*\((.*?)\)", ptx, re.DOTALL)
        if len(entries) != 1:
            raise RuntimeError("Expected exactly one CuTe DSL device kernel")
        name, params = entries[0]
        types = re.findall(r"\.param\s+\.(\w+)", params)
        if types != ["u64", "u64", "u64", "u32", "f32"]:
            raise RuntimeError(f"Unexpected CuTe DSL PTX ABI: {types}")
        # Pointer order follows the explicitly declared kernel parameters:
        # output, input, weight, dim, eps. Reject extra launch requirements.
        if not re.search(r"\.reqntid\s+32,\s*1,\s*1", ptx) or ".shared" in ptx:
            raise RuntimeError("Unexpected CuTe DSL thread/shared-memory requirements")
        target = re.search(r"\.target\s+(sm_\w+)", ptx)
        if target is None or target[1] != arch:
            raise RuntimeError(f"CuTe DSL emitted an unexpected architecture: {target}")
        image = compiled.artifacts.CUBIN
        if isinstance(image, str):
            image = Path(image).read_bytes()
        if not isinstance(image, bytes) or not image.startswith(b"\x7fELF"):
            raise RuntimeError("CuTe DSL did not return an ELF cubin")
        cubin = out_dir / f"cute_dsl_rmsnorm_{dtype_id}_sm{sm}.cubin"
        cubin.write_bytes(image)
        cubin.with_suffix(".ptx").write_text(ptx)
        # A runtime loop handles all sizes; reuse the image for the shared
        # dispatcher's existing power-of-two shape buckets.
        for block in BLOCKS:
            lines.append(
                f"    KernelSpec {{ dtype: {dtype_id}, block: {block}, "
                f"image: include_bytes!({json.dumps(str(cubin), ensure_ascii=False)}), "
                f'name: b"{name}\\0", shared: 0, threads: 32, '
                "pointer_order: [0, 1, 2] },"
            )
    lines.append("];")
    (out_dir / "cute_dsl_kernels.rs").write_text("\n".join(lines) + "\n")
    print(f"Compiled 3 CuTe DSL RMSNorm kernels for {arch} (30 shape entries)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--arch", required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args()
    try:
        compile_kernels(args.arch, args.out_dir)
    except Exception as exc:
        parser.exit(1, f"CuTe DSL AOT compilation failed: {exc}\n")


if __name__ == "__main__":
    main()
