#!/usr/bin/env python3
"""Compile RMSNorm cubins and their Rust manifest without a GPU or PyTorch.

The pinned compiler version is part of the launcher ABI. In particular, Triton
3.6.0 adds global/profile scratch pointers after the five explicit arguments;
the Rust launcher passes null for these after we check no scratch is required.
"""

import argparse
import json
import re
import sys
from pathlib import Path


TRITON_VERSION = "3.6.0"
DTYPES = ((0, "fp32"), (1, "fp16"), (2, "bf16"))
BLOCKS = tuple(1 << power for power in range(5, 15))


def compile_kernels(arch: str, out_dir: Path) -> None:
    # Keep generated __pycache__ files out of Cargo's watched source directory.
    sys.dont_write_bytecode = True
    try:
        import triton
    except ImportError as exc:
        raise RuntimeError(
            f"Triton is not installed in {sys.executable}. "
            f"Install triton=={TRITON_VERSION} and set RUSTINFER_TRITON_PYTHON "
            "to that Python interpreter."
        ) from exc
    if triton.__version__ != TRITON_VERSION:
        raise RuntimeError(
            f"Expected triton=={TRITON_VERSION}, found {triton.__version__}; "
            "the pinned version is required by the Rust launch ABI."
        )

    from triton.backends.compiler import GPUTarget
    from triton.compiler import ASTSource

    from rmsnorm import rmsnorm

    match = re.fullmatch(r"sm_([0-9]+)a?", arch)
    if match is None or int(match[1]) < 80:
        raise ValueError(f"Triton RMSNorm requires CUDA_ARCH=sm_80 or newer, got {arch!r}")
    sm = int(match[1])
    target = GPUTarget("cuda", sm, 32)
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by triton/compile.py; do not edit.",
        f"pub(crate) const TARGET_SM: i32 = {sm};",
        "pub(crate) static KERNELS: &[KernelSpec] = &[",
    ]
    for dtype_id, dtype in DTYPES:
        for block in BLOCKS:
            # No pointer divisibility hints: contiguous sliced tensors need not
            # have aligned base pointers. dim and eps remain runtime arguments.
            source = ASTSource(
                fn=rmsnorm,
                signature={
                    "output": f"*{dtype}",
                    "input": f"*{dtype}",
                    "weight": f"*{dtype}",
                    "dim": "i32",
                    "eps": "fp32",
                    "BLOCK": "constexpr",
                },
                constexprs={"BLOCK": block},
            )
            kernel = triton.compile(
                source,
                target=target,
                options={
                    "num_warps": 4 if block <= 2048 else 8,
                    "num_ctas": 1,
                    "enable_fp_fusion": False,
                    "launch_cooperative_grid": False,
                    "launch_pdl": False,
                },
            )
            metadata = kernel.metadata
            if (
                metadata.global_scratch_size != 0
                or metadata.profile_scratch_size != 0
                or metadata.num_ctas != 1
                or metadata.launch_cooperative_grid
                or metadata.launch_pdl
                or metadata.target != target
                or metadata.shared > 48 * 1024
            ):
                raise RuntimeError(f"Unsupported launch requirements for {dtype}/{block}: {metadata}")
            if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", metadata.name):
                raise RuntimeError(f"Invalid kernel symbol: {metadata.name!r}")

            # Check the compiled ABI, including the two null scratch pointers.
            parameters = re.search(
                rf"\.visible\s+\.entry\s+{re.escape(metadata.name)}\s*\((.*?)\)",
                kernel.asm["ptx"],
                re.DOTALL,
            )
            types = re.findall(r"\.param\s+\.(\w+)", parameters[1]) if parameters else []
            if types != ["u64", "u64", "u64", "u32", "f32", "u64", "u64"]:
                raise RuntimeError(f"Unexpected Triton launch ABI for {dtype}/{block}: {types}")

            cubin = out_dir / f"rmsnorm_{dtype}_{block}_sm{sm}.cubin"
            cubin.write_bytes(kernel.asm["cubin"])
            # JSON quoting is also Rust string quoting for ordinary paths; leave
            # Unicode intact rather than emitting JSON-only \\uXXXX escapes.
            path_literal = json.dumps(str(cubin), ensure_ascii=False)
            lines.append(
                f"    KernelSpec {{ dtype: {dtype_id}, block: {block}, "
                f"image: include_bytes!({path_literal}), name: b\"{metadata.name}\\0\", "
                f"shared: {metadata.shared}, threads: {metadata.num_warps * target.warp_size} }},"
            )
    lines.append("];")
    (out_dir / "triton_kernels.rs").write_text("\n".join(lines) + "\n")
    print(f"Compiled {len(DTYPES) * len(BLOCKS)} Triton RMSNorm kernels for sm_{sm} into {out_dir}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--arch", required=True, help="CUDA architecture, e.g. sm_89")
    parser.add_argument("--out-dir", required=True, type=Path)
    args = parser.parse_args()
    try:
        compile_kernels(args.arch, args.out_dir)
    except Exception as exc:
        parser.exit(1, f"RustInfer Triton AOT compilation failed: {exc}\n")


if __name__ == "__main__":
    main()
