#!/usr/bin/env python3
"""Compile pinned TileLang RMSNorm to cubins and a checked Rust launch manifest."""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

TILELANG_VERSION = "0.1.14"
DTYPES = ((0, "float32"), (1, "float16"), (2, "bfloat16"))
BLOCKS = tuple(1 << power for power in range(5, 15))


def compile_kernels(arch: str, out_dir: Path) -> None:
    sys.dont_write_bytecode = True
    try:
        import tilelang
    except ImportError as exc:
        raise RuntimeError(
            f"Install tilelang=={TILELANG_VERSION} in {sys.executable} and set "
            "RUSTINFER_TILELANG_PYTHON to that interpreter."
        ) from exc
    if tilelang.__version__ != TILELANG_VERSION:
        raise RuntimeError(f"Expected tilelang=={TILELANG_VERSION}, found {tilelang.__version__}")
    match = re.fullmatch(r"sm_([0-9]+)a?", arch)
    if match is None or int(match[1]) < 80:
        raise ValueError(f"TileLang RMSNorm requires sm_80 or newer, got {arch!r}")
    sm = int(match[1])
    from tilelang import tvm
    from rmsnorm import rmsnorm

    nvcc = os.environ.get("NVCC") or shutil.which("nvcc")
    if not nvcc:
        raise RuntimeError("nvcc not found; set NVCC or add CUDA bin to PATH")
    ptxas = Path(nvcc).resolve().with_name("ptxas")
    package = Path(tilelang.__file__).resolve().parent
    includes = [package / "src", package / "3rdparty/cutlass/include"]
    target = tvm.target.Target({"kind": "cuda", "arch": arch})
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by tilelang/compile.py; do not edit.",
        f"pub(crate) const TARGET_SM: i32 = {sm};",
        "pub(crate) static KERNELS: &[KernelSpec] = &[",
    ]
    for dtype_id, dtype in DTYPES:
        for block in BLOCKS:
            with tilelang.transform.PassContext(opt_level=3, config={"tirx.noalias": False}), target:
                artifact = tilelang.lower(
                    rmsnorm(dtype, max(block, 128)), target=target,
                    enable_device_compile=False, enable_host_codegen=False,
                )
            functions = list(artifact.device_mod.functions.items())
            if len(functions) != 1:
                raise RuntimeError("Expected exactly one TileLang device kernel")
            symbol, function = functions[0]
            name = symbol.name_hint
            params = [p.name for p in function.params]
            # TileLang reorders pointer parameters during device lowering.
            if params != ["W", "X", "Y", "dim", "eps"]:
                raise RuntimeError(f"Unexpected TileLang parameter order: {params}")
            extents = {str(k): int(v) for k, v in function.attrs["thread_extent"].items()}
            if extents != {"blockIdx.x": 2147483647, "threadIdx.x": 128,
                           "threadIdx.y": 1, "threadIdx.z": 1}:
                raise RuntimeError(f"Unexpected launch dimensions: {extents}")
            shared = int(function.attrs.get("dyn_shared_memory_buf", 0))
            if shared > 48 * 1024 or not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", name):
                raise RuntimeError(f"Unsupported kernel metadata: {function.attrs}")
            source = str(artifact.kernel_source)
            # In-place RMSNorm aliases X/Y; reject a compiler that loses the annotation.
            if re.search(r"__restrict__\s+[XY]\b", source):
                raise RuntimeError("TileLang lost the in-place alias annotation")
            stem = out_dir / f"tilelang_rmsnorm_{dtype}_{block}_sm{sm}"
            cu, ptx, cubin = (stem.with_suffix(s) for s in (".cu", ".ptx", ".cubin"))
            cu.write_text(source)
            command = [nvcc, "--ptx", "-O3", "-std=c++17", "--fmad=false",
                       "--expt-relaxed-constexpr", f"-arch={arch}"]
            for include in includes:
                command.extend(["-I", str(include)])
            subprocess.run(command + [str(cu), "-o", str(ptx)], check=True, capture_output=True, text=True)
            parameters = re.search(
                rf"\.visible\s+\.entry\s+{re.escape(name)}\s*\((.*?)\)",
                ptx.read_text(), re.DOTALL,
            )
            types = re.findall(r"\.param\s+\.(\w+)", parameters[1]) if parameters else []
            if types != ["u64", "u64", "u64", "u32", "f32"]:
                raise RuntimeError(f"Unexpected TileLang PTX ABI: {types}")
            subprocess.run([str(ptxas), f"-arch={arch}", str(ptx), "-o", str(cubin)],
                           check=True, capture_output=True, text=True)
            lines.append(
                f"    KernelSpec {{ dtype: {dtype_id}, block: {block}, "
                f"image: include_bytes!({json.dumps(str(cubin), ensure_ascii=False)}), "
                f'name: b"{name}\\0", shared: {shared}, threads: 128, '
                "pointer_order: [2, 1, 0] },"
            )
    lines.append("];")
    (out_dir / "tilelang_kernels.rs").write_text("\n".join(lines) + "\n")
    print(f"Compiled {len(DTYPES) * len(BLOCKS)} TileLang RMSNorm kernels for {arch}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--arch", required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args()
    try:
        compile_kernels(args.arch, args.out_dir)
    except subprocess.CalledProcessError as exc:
        parser.exit(1, f"TileLang CUDA compilation failed: {exc}\n{exc.stdout}\n{exc.stderr}\n")
    except Exception as exc:
        parser.exit(1, f"TileLang AOT compilation failed: {exc}\n")


if __name__ == "__main__":
    main()
