//! Type-state inference session lifecycle.
//!
//! A session is represented as `InferenceSession<S>` where `S` is one of the
//! sealed state types (`Queued` / `Prefilling` / `Decoding` / `Finished` /
//! `Failed`). State transitions consume the old value and produce a new type —
//! making invalid state access a compile-time error.
//!
//! ## Sealed trait
//!
//! `SessionState` is sealed: only the five state types in this module
//! implement it. External crates cannot extend the state machine, which keeps
//! the invariants centralized.

use std::sync::Arc;
use std::time::Instant;

use crate::domain::kv_cache_pool::KvLease;
use crate::infrastructure::kv_cache::traits::PrefixMatch;
use crate::domain::inference_session::handle::RequestHandle;
use infer_protocol::server_to_scheduler::DiffusionRequest;

// ═══════════════════════════════════════════════════════════════════════════════
//  Request Identity & Metadata
// ═══════════════════════════════════════════════════════════════════════════════

/// Internal scheduler-assigned request id.
///
/// **This is NOT the client-supplied request id.** The client's original
/// string id is preserved as [`RequestMeta::external_id`] for response
/// routing. Internally the scheduler uses a freshly generated `uuid::Uuid` —
/// this avoids:
/// - duplicate ids if a buggy client reuses the same string
/// - id-injection / cache-poisoning attacks
/// - inconsistent hashing of arbitrary user strings on the hot path
///
/// Generated by [`RequestId::new_v4`] in `IngestionSystem`. Equality/hash on
/// the inner `Uuid` is O(1) bytewise.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct RequestId(uuid::Uuid);

impl RequestId {
    /// Generate a fresh v4 UUID-backed id for a new request.
    pub fn new_v4() -> Self {
        Self(uuid::Uuid::new_v4())
    }

    /// Build from an existing UUID (for tests or deserialization).
    pub fn from_uuid(uuid: uuid::Uuid) -> Self {
        Self(uuid)
    }

    /// Borrow the underlying UUID (for hashing/serialization paths
    /// that need the raw value).
    pub fn as_uuid(&self) -> &uuid::Uuid {
        &self.0
    }
}

impl std::fmt::Display for RequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Standard UUID format (36 chars with hyphens), e.g.
        // "550e8400-e29b-41d4-a716-446655440000"
        write!(f, "{}", self.0)
    }
}

/// Compact scheduler-assigned id used on the Worker hot path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SequenceId(pub u64);

impl std::fmt::Display for SequenceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Priority level (higher = more important).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
#[derive(Default)]
pub struct Priority(pub i32);


/// Sampling parameters.
#[derive(Debug, Clone)]
pub struct SamplingParams {
    pub temperature: f32,
    pub top_p: f32,
    pub top_k: i32,
}

impl Default for SamplingParams {
    fn default() -> Self {
        Self {
            temperature: 0.0,
            top_p: 1.0,
            top_k: -1,
        }
    }
}

/// Shared immutable request metadata (Arc'd, never changes after creation).
#[derive(Debug, Clone)]
pub struct RequestMeta {
    /// Internal scheduler id (uuid). Used for hashing, scheduling, logging.
    pub id: RequestId,
    /// Client-supplied id from the HTTP request body (e.g. `request_id`
    /// in OpenAI ChatCompletionRequest). **Echoed verbatim** in responses
    /// so clients can correlate. May be empty if the client did not send one.
    pub external_id: String,
    pub sequence_id: SequenceId,
    pub input_ids: Vec<i32>,
    pub max_tokens: usize,
    pub sampling: SamplingParams,
    pub priority: Priority,
    pub stream: bool,
    pub stop_sequences: Vec<Vec<i32>>,
    pub diffusion: Option<DiffusionRequest>,
    pub arrival_time: Instant,
}

// ═══════════════════════════════════════════════════════════════════════════════
//  SessionState — sealed trait + 5 state types
// ═══════════════════════════════════════════════════════════════════════════════

mod sealed {
    pub trait Sealed {}
}

/// Marker trait for an inference-session lifecycle stage.
///
/// **Sealed**: only the five state types in this module implement it. The
/// state machine cannot be extended by external crates.
pub trait SessionState: sealed::Sealed {}

/// Data for a queued (waiting) session.
pub struct Queued {
    /// Prefix match result (computed on enqueue for cache-aware scheduling).
    pub prefix_match: Option<PrefixMatch>,
}

/// Data for a session actively being prefilled.
pub struct Prefilling {
    pub kv_lease: KvLease,
    /// How many prompt tokens the Worker has acknowledged as written to KV.
    pub num_computed_tokens: usize,
    /// Segment already sent to Worker but not yet acknowledged.
    pub inflight: Option<InFlightPrefillSegment>,
    pub prompt_len: usize,
    pub prefill_start: Instant,
}

#[derive(Debug, Clone, Copy)]
pub struct InFlightPrefillSegment {
    pub segment_start: usize,
    pub segment_end: usize,
    pub is_final: bool,
}

/// Data for a session in the decode phase.
pub struct Decoding {
    pub kv_lease: KvLease,
    pub output_tokens: Vec<i32>,
    pub seq_position: usize,
    pub prompt_len: usize,
    pub first_token_time: Instant,
    pub preemption_count: u32,
}

/// Reason a session finished successfully.
#[derive(Debug, Clone)]
pub enum FinishReason {
    Eos,
    MaxTokens,
    StopSequence,
    Error(String),
    Cancelled,
}

/// Data for a successfully finished session.
pub struct Finished {
    pub finish_reason: FinishReason,
    pub output_tokens: Vec<i32>,
    pub metrics: CompletionMetrics,
    /// KV allocation kept for the OutputProcessing system to free during
    /// `flush_terminals` (RAII Drop guard arrival in Step 11 will fold this
    /// into automatic cleanup).
    pub kv_lease: KvLease,
}

/// Data for a session that errored / was killed.
///
/// **Invariant**: `Failed` always carries the KV allocation so the cleanup
/// path is uniform with `Finished`. Sessions that fail before any KV is
/// allocated (e.g. validation reject in Ingestion) should be dropped from
/// the repository directly without transitioning through `Failed`.
pub struct Failed {
    pub message: String,
    pub kv_lease: KvLease,
    pub partial_output_tokens: Vec<i32>,
}

/// Per-request completion metrics.
#[derive(Debug, Clone)]
pub struct CompletionMetrics {
    pub ttft: std::time::Duration,
    pub e2e_latency: std::time::Duration,
    pub num_output_tokens: u32,
    pub num_preemptions: u32,
}

/// Data for a session that was preempted by the admission cascade
/// (Phase 6 / plan §7). Generated tokens are dropped; prompt is preserved
/// in `Arc<RequestMeta>` so the session can be re-queued and re-prefilled.
/// `KvLease` is intentionally absent — it is consumed by `preempt_to_starved`
/// and dropped (returning blocks to the legacy block sink) at the moment
/// the new RadixTree path marks the chain finished.
pub struct ResourceStarved {
    pub dropped_output_count: u32,
    pub preemption_count: u32,
}

impl sealed::Sealed for Queued {}
impl sealed::Sealed for Prefilling {}
impl sealed::Sealed for Decoding {}
impl sealed::Sealed for Finished {}
impl sealed::Sealed for Failed {}
impl sealed::Sealed for ResourceStarved {}

impl SessionState for Queued {}
impl SessionState for Prefilling {}
impl SessionState for Decoding {}
impl SessionState for Finished {}
impl SessionState for Failed {}
impl SessionState for ResourceStarved {}

// ═══════════════════════════════════════════════════════════════════════════════
//  InferenceSession<S> — parameterized by state data
// ═══════════════════════════════════════════════════════════════════════════════

/// A session at a specific lifecycle stage.
///
/// The type parameter `S: SessionState` is the state-specific data struct.
/// Different states expose different methods — enforced at compile time.
///
/// State diagram:
/// ```text
///   Queued ──start_prefill(kv)──▶ Prefilling ──promote_to_decoding──▶ Decoding
///                                       │                                │
///                                       └──────fail(msg)──────▶ Failed ◀┘
///                                                                ▲
///                                          Decoding ─finish(reason)── Finished
/// ```
///
/// **No `Queued::fail()`**: a queued session that fails (e.g. validation
/// reject) never had KV allocated, so it should be dropped from the
/// repository, not transitioned to `Failed`. This keeps `Failed::kv_alloc`
/// non-optional.
pub struct InferenceSession<S: SessionState> {
    /// Shared immutable metadata.
    pub meta: Arc<RequestMeta>,
    /// Response channel back to the HTTP server.
    pub handle: RequestHandle,
    /// State-specific data.
    pub state: S,
}

// ═══════════════════════════════════════════════════════════════════════════════
//  State Transitions — ownership transfer guarantees validity
// ═══════════════════════════════════════════════════════════════════════════════

impl InferenceSession<Queued> {
    /// Create a new queued session.
    pub fn new(meta: Arc<RequestMeta>, handle: RequestHandle) -> Self {
        Self {
            meta,
            handle,
            state: Queued { prefix_match: None },
        }
    }

    /// Set prefix match result.
    pub fn with_prefix_match(mut self, prefix_match: PrefixMatch) -> Self {
        self.state.prefix_match = Some(prefix_match);
        self
    }

    /// Transition: Queued → Prefilling.
    pub fn start_prefill(self, kv_lease: KvLease) -> InferenceSession<Prefilling> {
        let prompt_len = self.meta.input_ids.len();
        InferenceSession {
            meta: self.meta,
            handle: self.handle,
            state: Prefilling {
                kv_lease,
                num_computed_tokens: 0,
                inflight: None,
                prompt_len,
                prefill_start: Instant::now(),
            },
        }
    }

    /// Get the request ID.
    pub fn id(&self) -> &RequestId {
        &self.meta.id
    }
}

impl InferenceSession<Prefilling> {
    /// Transition: Prefilling → Decoding (when prefill is complete).
    pub fn start_decode(self) -> InferenceSession<Decoding> {
        debug_assert!(
            self.state.num_computed_tokens >= self.state.prompt_len,
            "start_decode called before prefill complete: {} < {}",
            self.state.num_computed_tokens,
            self.state.prompt_len,
        );
        InferenceSession {
            meta: self.meta,
            handle: self.handle,
            state: Decoding {
                kv_lease: self.state.kv_lease,
                output_tokens: Vec::new(),
                seq_position: self.state.prompt_len,
                prompt_len: self.state.prompt_len,
                first_token_time: Instant::now(),
                preemption_count: 0,
            },
        }
    }

    /// Transition: Prefilling → Failed (carries KV for cleanup).
    pub fn fail(self, message: String) -> InferenceSession<Failed> {
        InferenceSession {
            meta: self.meta,
            handle: self.handle,
            state: Failed {
                message,
                kv_lease: self.state.kv_lease,
                partial_output_tokens: Vec::new(),
            },
        }
    }

    /// Mark an in-flight segment as completed by the Worker.
    pub fn ack_inflight(&mut self) -> Option<InFlightPrefillSegment> {
        let inflight = self.state.inflight.take()?;
        self.state.num_computed_tokens = inflight.segment_end;
        Some(inflight)
    }

    /// Mark a segment as sent to Worker.
    pub fn set_inflight(&mut self, segment_start: usize, segment_end: usize) {
        self.state.inflight = Some(InFlightPrefillSegment {
            segment_start,
            segment_end,
            is_final: segment_end >= self.state.prompt_len,
        });
    }

    /// Whether this session has a segment in flight.
    pub fn has_inflight(&self) -> bool {
        self.state.inflight.is_some()
    }

    /// Advance: chunk completed, more to go.
    pub fn advance_chunk(&mut self, tokens_processed: usize) {
        self.state.num_computed_tokens += tokens_processed;
    }

    /// Check if prefill is complete.
    pub fn is_complete(&self) -> bool {
        self.state.num_computed_tokens >= self.state.prompt_len
    }

    /// Remaining tokens to prefill.
    pub fn remaining_tokens(&self) -> usize {
        self.state.prompt_len.saturating_sub(self.state.num_computed_tokens)
    }

    /// Get the request ID.
    pub fn id(&self) -> &RequestId {
        &self.meta.id
    }
}

impl InferenceSession<Decoding> {
    /// Transition: Decoding → Finished (carries KV for cleanup).
    pub fn finish(self, reason: FinishReason) -> InferenceSession<Finished> {
        let ttft = self.state.first_token_time.duration_since(self.meta.arrival_time);
        let e2e = self.meta.arrival_time.elapsed();
        let num_tokens = self.state.output_tokens.len() as u32;

        InferenceSession {
            meta: self.meta,
            handle: self.handle,
            state: Finished {
                finish_reason: reason,
                output_tokens: self.state.output_tokens,
                metrics: CompletionMetrics {
                    ttft,
                    e2e_latency: e2e,
                    num_output_tokens: num_tokens,
                    num_preemptions: self.state.preemption_count,
                },
                kv_lease: self.state.kv_lease,
            },
        }
    }

    /// Transition: Decoding → Failed (carries KV + partial output).
    pub fn fail(self, message: String) -> InferenceSession<Failed> {
        InferenceSession {
            meta: self.meta,
            handle: self.handle,
            state: Failed {
                message,
                kv_lease: self.state.kv_lease,
                partial_output_tokens: self.state.output_tokens,
            },
        }
    }

    /// Append a generated token.
    pub fn append_token(&mut self, token_id: i32) {
        self.state.output_tokens.push(token_id);
        self.state.seq_position += 1;
    }

    /// Number of tokens generated so far.
    pub fn num_generated(&self) -> usize {
        self.state.output_tokens.len()
    }

    /// Whether max_tokens has been reached.
    pub fn reached_max_tokens(&self) -> bool {
        self.state.output_tokens.len() >= self.meta.max_tokens
    }

    /// Preempt: Decoding → Queued (for recompute strategy).
    /// Returns the queued session and the lease (caller is responsible
    /// for releasing it back to the pool).
    pub fn preempt_recompute(self) -> (InferenceSession<Queued>, KvLease) {
        let kv_lease = self.state.kv_lease;
        let seq = InferenceSession {
            meta: self.meta,
            handle: self.handle,
            state: Queued { prefix_match: None },
        };
        (seq, kv_lease)
    }

    /// Preempt: Decoding → ResourceStarved (Phase 6 / plan §7).
    ///
    /// Used by the admission cascade when KV pressure forces the engine
    /// to evict a live decoder. Generated tokens are dropped; the prompt
    /// (in `Arc<RequestMeta>`) survives and the session can be lifted
    /// back into the waiting queue via [`InferenceSession::<ResourceStarved>::requeue`].
    ///
    /// Returns the new typed session and the legacy `KvLease`. In the
    /// new RadixTree-driven path the lease is empty (the worker-side
    /// indices have already been marked finished and will be reclaimed
    /// by the next `FreeKvIndices` round). In the legacy path the
    /// caller drops the lease, returning blocks to the block sink.
    pub fn preempt_to_starved(self) -> (InferenceSession<ResourceStarved>, KvLease) {
        let kv_lease = self.state.kv_lease;
        let dropped_output_count = self.state.output_tokens.len() as u32;
        let preemption_count = self.state.preemption_count + 1;
        let seq = InferenceSession {
            meta: self.meta,
            handle: self.handle,
            state: ResourceStarved {
                dropped_output_count,
                preemption_count,
            },
        };
        (seq, kv_lease)
    }

    /// Get the request ID.
    pub fn id(&self) -> &RequestId {
        &self.meta.id
    }
}

impl InferenceSession<ResourceStarved> {
    /// Lift a preempted session back into the waiting queue. The same
    /// `RequestMeta` (which holds the prompt) is preserved; preemption
    /// count is carried forward so policies can apply backoff.
    pub fn requeue(self) -> InferenceSession<Queued> {
        InferenceSession {
            meta: self.meta,
            handle: self.handle,
            // No prefix_match snapshot here; the next admission lookup
            // (driven by RadixTree::lookup_prefix in the new path) will
            // recompute it. The legacy field is `Option`-y for exactly
            // this reason.
            state: Queued { prefix_match: None },
        }
    }

    /// Number of output tokens that were dropped on preemption. Useful
    /// for metrics; the actual content is gone.
    pub fn dropped_output_count(&self) -> u32 {
        self.state.dropped_output_count
    }

    pub fn preemption_count(&self) -> u32 {
        self.state.preemption_count
    }

    pub fn id(&self) -> &RequestId {
        &self.meta.id
    }
}

impl InferenceSession<Finished> {
    /// Get the request ID.
    pub fn id(&self) -> &RequestId {
        &self.meta.id
    }
}

impl InferenceSession<Failed> {
    /// Get the request ID.
    pub fn id(&self) -> &RequestId {
        &self.meta.id
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
//  AnySession — runtime enum for heterogeneous storage
// ═══════════════════════════════════════════════════════════════════════════════

/// Runtime wrapper for sessions in any active lifecycle state.
///
/// Repository code uses `AnySession` only for cancel/diagnostic paths; hot
/// transitions go through typed variants directly.
pub enum AnySession {
    Queued(InferenceSession<Queued>),
    Prefilling(InferenceSession<Prefilling>),
    Decoding(InferenceSession<Decoding>),
}

impl AnySession {
    /// Get the request ID regardless of state.
    pub fn id(&self) -> &RequestId {
        match self {
            Self::Queued(s) => &s.meta.id,
            Self::Prefilling(s) => &s.meta.id,
            Self::Decoding(s) => &s.meta.id,
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
//  Tests — typestate transition correctness
// ═══════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use crate::infrastructure::kv_cache::traits::PhysicalBlockId;

    fn make_meta(prompt_len: usize) -> Arc<RequestMeta> {
        Arc::new(RequestMeta {
            id: RequestId::new_v4(),
            external_id: "test".into(),
            sequence_id: SequenceId(1),
            input_ids: (0..prompt_len as i32).collect(),
            max_tokens: 32,
            sampling: SamplingParams::default(),
            priority: Priority::default(),
            stream: false,
            stop_sequences: vec![],
            diffusion: None,
            arrival_time: Instant::now(),
        })
    }

    fn paged_alloc() -> KvLease {
        // Tests use a detached lease (no return sink): drop is a no-op,
        // matching what the engine sees in the legacy `KvAllocation`
        // shape but typed as the new `KvLease`.
        KvLease::test_with_blocks(vec![PhysicalBlockId(7), PhysicalBlockId(8)])
    }

    #[test]
    fn queued_to_prefilling_transfers_meta_and_sets_kv() {
        let s = InferenceSession::<Queued>::new(make_meta(4), RequestHandle::noop());
        let s = s.start_prefill(paged_alloc());
        assert_eq!(s.state.prompt_len, 4);
        assert_eq!(s.state.num_computed_tokens, 0);
        assert!(s.state.inflight.is_none());
        let _ = s.state.kv_lease.blocks();
    }

    #[test]
    fn prefilling_to_decoding_after_complete() {
        let s = InferenceSession::<Queued>::new(make_meta(4), RequestHandle::noop());
        let mut s = s.start_prefill(paged_alloc());
        s.advance_chunk(4);
        assert!(s.is_complete());
        let s = s.start_decode();
        assert_eq!(s.state.seq_position, 4);
        assert_eq!(s.state.prompt_len, 4);
    }

    #[test]
    fn decoding_to_finished_carries_kv() {
        let q = InferenceSession::<Queued>::new(make_meta(2), RequestHandle::noop());
        let mut p = q.start_prefill(paged_alloc());
        p.advance_chunk(2);
        let mut d = p.start_decode();
        d.append_token(99);
        let f = d.finish(FinishReason::Eos);
        assert_eq!(f.state.output_tokens, vec![99]);
        // Finished must carry kv_alloc for cleanup.
        assert!(!f.state.kv_lease.blocks().is_empty());
    }

    #[test]
    fn prefilling_fail_carries_kv() {
        let q = InferenceSession::<Queued>::new(make_meta(2), RequestHandle::noop());
        let p = q.start_prefill(paged_alloc());
        let f = p.fail("worker error".into());
        assert_eq!(f.state.message, "worker error");
        // Failed must carry kv_alloc for cleanup.
        assert!(!f.state.kv_lease.blocks().is_empty());
        assert!(f.state.partial_output_tokens.is_empty());
    }

    #[test]
    fn decoding_fail_preserves_partial_output() {
        let q = InferenceSession::<Queued>::new(make_meta(2), RequestHandle::noop());
        let mut p = q.start_prefill(paged_alloc());
        p.advance_chunk(2);
        let mut d = p.start_decode();
        d.append_token(11);
        d.append_token(22);
        let f = d.fail("oom".into());
        assert_eq!(f.state.partial_output_tokens, vec![11, 22]);
        let _ = f.state.kv_lease.blocks();
    }

    #[test]
    fn decoding_preempt_to_starved_drops_outputs_and_bumps_count() {
        let q = InferenceSession::<Queued>::new(make_meta(4), RequestHandle::noop());
        let mut p = q.start_prefill(paged_alloc());
        p.advance_chunk(4);
        let mut d = p.start_decode();
        d.append_token(99);
        d.append_token(100);
        d.append_token(101);
        let prompt_before = d.meta.input_ids.clone();
        let id_before = *d.id();

        let (starved, lease) = d.preempt_to_starved();
        assert_eq!(starved.dropped_output_count(), 3);
        assert_eq!(starved.preemption_count(), 1);
        // Prompt preserved verbatim through the Arc<RequestMeta>.
        assert_eq!(starved.meta.input_ids, prompt_before);
        assert_eq!(*starved.id(), id_before);
        // Legacy lease passed back to the caller.
        assert!(!lease.blocks().is_empty());
    }

    #[test]
    fn starved_requeue_returns_to_queued() {
        let q = InferenceSession::<Queued>::new(make_meta(4), RequestHandle::noop());
        let mut p = q.start_prefill(paged_alloc());
        p.advance_chunk(4);
        let d = p.start_decode();
        let id_before = *d.id();
        let (starved, _lease) = d.preempt_to_starved();
        let q2 = starved.requeue();
        // Re-queued session has the same id, same prompt.
        assert_eq!(*q2.id(), id_before);
        assert_eq!(q2.meta.input_ids.len(), 4);
        assert!(q2.state.prefix_match.is_none());
    }

    #[test]
    fn preempt_to_starved_carries_forward_existing_preemption_count() {
        // Construct a Decoding with preemption_count > 0 directly.
        let meta = make_meta(2);
        let session: InferenceSession<Decoding> = InferenceSession {
            meta: meta.clone(),
            handle: RequestHandle::noop(),
            state: Decoding {
                kv_lease: paged_alloc(),
                output_tokens: vec![1, 2, 3],
                seq_position: 5,
                prompt_len: 2,
                first_token_time: Instant::now(),
                preemption_count: 2,
            },
        };
        let (starved, _lease) = session.preempt_to_starved();
        assert_eq!(starved.preemption_count(), 3, "must increment");
    }
}

