//! Type-state inference session lifecycle.
//!
//! A session is represented as `InferenceSession<S>` where `S` is one of the
//! sealed state types (`Queued` / `Prefilling` / `Decoding` / `Finished` /
//! `Failed`). State transitions consume the old value and produce a new type —
//! making invalid state access a compile-time error.
//!
//! ## Sealed trait
//!
//! `SessionState` is sealed: only the five state types in this module
//! implement it. External crates cannot extend the state machine, which keeps
//! the invariants centralized.

use std::sync::Arc;
use std::time::Instant;

use crate::domain::inference_session::handle::RequestHandle;
use crate::infrastructure::kv_cache::traits::PrefixMatch;
use infer_protocol::server_to_scheduler::DiffusionRequest;

// ═══════════════════════════════════════════════════════════════════════════════
//  Request Identity & Metadata
// ═══════════════════════════════════════════════════════════════════════════════

/// Internal scheduler-assigned request id.
///
/// **This is NOT the client-supplied request id.** The client's original
/// string id is preserved as [`RequestMeta::external_id`] for response
/// routing. Internally the scheduler uses a freshly generated `uuid::Uuid` —
/// this avoids:
/// - duplicate ids if a buggy client reuses the same string
/// - id-injection / cache-poisoning attacks
/// - inconsistent hashing of arbitrary user strings on the hot path
///
/// Generated by [`RequestId::new_v4`] in `IngestionSystem`. Equality/hash on
/// the inner `Uuid` is O(1) bytewise.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct RequestId(uuid::Uuid);

impl RequestId {
    /// Generate a fresh v4 UUID-backed id for a new request.
    pub fn new_v4() -> Self {
        Self(uuid::Uuid::new_v4())
    }
}

impl std::fmt::Display for RequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Standard UUID format (36 chars with hyphens), e.g.
        // "550e8400-e29b-41d4-a716-446655440000"
        write!(f, "{}", self.0)
    }
}

/// Compact scheduler-assigned id used on the Worker hot path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SequenceId(pub u64);

impl std::fmt::Display for SequenceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Priority level (higher = more important).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Default)]
pub struct Priority(pub i32);

/// Sampling parameters.
#[derive(Debug, Clone)]
pub struct SamplingParams {
    pub temperature: f32,
    pub top_p: f32,
    pub top_k: i32,
}

impl Default for SamplingParams {
    fn default() -> Self {
        Self {
            temperature: 0.0,
            top_p: 1.0,
            top_k: -1,
        }
    }
}

/// Shared immutable request metadata (Arc'd, never changes after creation).
#[derive(Debug, Clone)]
pub struct RequestMeta {
    /// Internal scheduler id (uuid). Used for hashing, scheduling, logging.
    pub id: RequestId,
    /// Client-supplied id from the HTTP request body (e.g. `request_id`
    /// in OpenAI ChatCompletionRequest). **Echoed verbatim** in responses
    /// so clients can correlate. May be empty if the client did not send one.
    pub external_id: String,
    pub sequence_id: SequenceId,
    pub input_ids: Vec<i32>,
    pub max_tokens: usize,
    pub sampling: SamplingParams,
    pub priority: Priority,
    pub stream: bool,
    pub stop_sequences: Vec<Vec<i32>>,
    /// Ignore EOS and decode to `max_tokens` (fixed-length benchmarking).
    pub ignore_eos: bool,
    pub diffusion: Option<DiffusionRequest>,
    pub arrival_time: Instant,
}

// ═══════════════════════════════════════════════════════════════════════════════
//  SessionState — sealed trait + 5 state types
// ═══════════════════════════════════════════════════════════════════════════════

mod sealed {
    pub trait Sealed {}
}

/// Marker trait for an inference-session lifecycle stage.
///
/// **Sealed**: only the five state types in this module implement it. The
/// state machine cannot be extended by external crates.
pub trait SessionState: sealed::Sealed {}

/// Data for a queued (waiting) session.
pub struct Queued {
    /// Prefix match result (computed on enqueue for cache-aware scheduling).
    pub prefix_match: Option<PrefixMatch>,
}

/// Data for a session actively being prefilled.
pub struct Prefilling {
    /// How many prompt tokens the Worker has acknowledged as written to KV.
    pub num_computed_tokens: usize,
    /// Segment already sent to Worker but not yet acknowledged.
    pub inflight: Option<InFlightPrefillSegment>,
    pub prompt_len: usize,
    pub prefill_start: Instant,
}

#[derive(Debug, Clone, Copy)]
pub struct InFlightPrefillSegment {
    pub segment_start: usize,
    pub segment_end: usize,
    pub is_final: bool,
}

/// Data for a session in the decode phase.
pub struct Decoding {
    pub output_tokens: Vec<i32>,
    pub seq_position: usize,
    pub prompt_len: usize,
    pub first_token_time: Instant,
    /// Number of times this session has been preempted by the worker
    /// under KV pressure. The current implementation does not yet
    /// receive worker-side preempt notifications; this counter is kept
    /// as a forward-compatible field so the eventual worker → scheduler
    /// preempt signal can bump it via [`InferenceSession::<Decoding>::bump_preempted`].
    pub preemption_count: u32,
}

/// Reason a session finished successfully.
#[derive(Debug, Clone)]
pub enum FinishReason {
    Eos,
    MaxTokens,
    StopSequence,
    Error(String),
    Cancelled,
}

/// Data for a successfully finished session.
pub struct Finished {
    pub finish_reason: FinishReason,
    pub output_tokens: Vec<i32>,
    pub metrics: CompletionMetrics,
}

/// Per-request completion metrics.
#[derive(Debug, Clone)]
pub struct CompletionMetrics {
    pub ttft: std::time::Duration,
    pub e2e_latency: std::time::Duration,
    pub num_output_tokens: u32,
    pub num_preemptions: u32,
}

impl sealed::Sealed for Queued {}
impl sealed::Sealed for Prefilling {}
impl sealed::Sealed for Decoding {}
impl sealed::Sealed for Finished {}

impl SessionState for Queued {}
impl SessionState for Prefilling {}
impl SessionState for Decoding {}
impl SessionState for Finished {}

// ═══════════════════════════════════════════════════════════════════════════════
//  InferenceSession<S> — parameterized by state data
// ═══════════════════════════════════════════════════════════════════════════════

/// A session at a specific lifecycle stage.
///
/// The type parameter `S: SessionState` is the state-specific data struct.
/// Different states expose different methods — enforced at compile time.
///
/// State diagram:
/// ```text
///   Queued ──start_prefill()──▶ Prefilling ──promote_to_decoding──▶ Decoding
///                                       │                                │
///                                       └──────fail(msg)──────▶ Failed ◀┘
///                                                                ▲
///                                          Decoding ─finish(reason)── Finished
/// ```
///
/// **No `Queued::fail()`**: a queued session that fails (e.g. validation
/// reject) is dropped from the repository directly rather than transitioning
/// to `Failed`. KV ownership lives on the worker; the scheduler signals
/// release via `RadixTree::mark_finished_chain` rather than through the
/// typed states.
pub struct InferenceSession<S: SessionState> {
    /// Shared immutable metadata.
    pub meta: Arc<RequestMeta>,
    /// Response channel back to the HTTP server.
    pub handle: RequestHandle,
    /// State-specific data.
    pub state: S,
}

// ═══════════════════════════════════════════════════════════════════════════════
//  State Transitions — ownership transfer guarantees validity
// ═══════════════════════════════════════════════════════════════════════════════

impl InferenceSession<Queued> {
    /// Create a new queued session.
    pub fn new(meta: Arc<RequestMeta>, handle: RequestHandle) -> Self {
        Self {
            meta,
            handle,
            state: Queued { prefix_match: None },
        }
    }

    /// Transition: Queued → Prefilling.
    pub fn start_prefill(self) -> InferenceSession<Prefilling> {
        let prompt_len = self.meta.input_ids.len();
        InferenceSession {
            meta: self.meta,
            handle: self.handle,
            state: Prefilling {
                num_computed_tokens: 0,
                inflight: None,
                prompt_len,
                prefill_start: Instant::now(),
            },
        }
    }
}

impl InferenceSession<Prefilling> {
    /// Transition: Prefilling → Decoding (when prefill is complete).
    pub fn start_decode(self) -> InferenceSession<Decoding> {
        debug_assert!(
            self.state.num_computed_tokens >= self.state.prompt_len,
            "start_decode called before prefill complete: {} < {}",
            self.state.num_computed_tokens,
            self.state.prompt_len,
        );
        // Pre-size `output_tokens` to dodge the 0→4→8→16→32→64 realloc
        // sequence on the hot path. 64 covers most short-completion
        // workloads (chat replies); longer outputs still amortize-grow
        // with one realloc per doubling. We cap the pre-allocation at
        // `max_tokens` so very small `max_tokens=8` requests don't
        // over-allocate either.
        let initial_cap = self.meta.max_tokens.min(64);
        InferenceSession {
            meta: self.meta,
            handle: self.handle,
            state: Decoding {
                output_tokens: Vec::with_capacity(initial_cap),
                seq_position: self.state.prompt_len,
                prompt_len: self.state.prompt_len,
                first_token_time: Instant::now(),
                preemption_count: 0,
            },
        }
    }

    /// Mark an in-flight segment as completed by the Worker.
    pub fn ack_inflight(&mut self) -> Option<InFlightPrefillSegment> {
        let inflight = self.state.inflight.take()?;
        self.state.num_computed_tokens = inflight.segment_end;
        Some(inflight)
    }

    /// Mark a segment as sent to Worker.
    pub fn set_inflight(&mut self, segment_start: usize, segment_end: usize) {
        self.state.inflight = Some(InFlightPrefillSegment {
            segment_start,
            segment_end,
            is_final: segment_end >= self.state.prompt_len,
        });
    }

    /// Whether this session has a segment in flight.
    pub fn has_inflight(&self) -> bool {
        self.state.inflight.is_some()
    }

    /// The in-flight segment, if one is currently dispatched-but-unacked.
    pub fn inflight_segment(&self) -> Option<InFlightPrefillSegment> {
        self.state.inflight
    }

    /// Check if prefill is complete.
    pub fn is_complete(&self) -> bool {
        self.state.num_computed_tokens >= self.state.prompt_len
    }

    /// Remaining tokens to prefill.
    pub fn remaining_tokens(&self) -> usize {
        self.state
            .prompt_len
            .saturating_sub(self.state.num_computed_tokens)
    }
}

impl InferenceSession<Decoding> {
    /// Transition: Decoding → Finished.
    pub fn finish(self, reason: FinishReason) -> InferenceSession<Finished> {
        let ttft = self
            .state
            .first_token_time
            .duration_since(self.meta.arrival_time);
        let e2e = self.meta.arrival_time.elapsed();
        let num_tokens = self.state.output_tokens.len() as u32;

        InferenceSession {
            meta: self.meta,
            handle: self.handle,
            state: Finished {
                finish_reason: reason,
                output_tokens: self.state.output_tokens,
                metrics: CompletionMetrics {
                    ttft,
                    e2e_latency: e2e,
                    num_output_tokens: num_tokens,
                    num_preemptions: self.state.preemption_count,
                },
            },
        }
    }

    /// Append a generated token.
    pub fn append_token(&mut self, token_id: i32) {
        self.state.output_tokens.push(token_id);
        self.state.seq_position += 1;
    }

    /// Whether max_tokens has been reached.
    pub fn reached_max_tokens(&self) -> bool {
        self.state.output_tokens.len() >= self.meta.max_tokens
    }

    /// Bump the preemption counter. Reserved hook for the future
    /// worker→scheduler preempt notification: when the worker's
    /// internal sub-scheduler kicks a sequence under KV starvation,
    /// it will tell the scheduler so the metric carries through.
    pub fn bump_preempted(&mut self) {
        self.state.preemption_count = self.state.preemption_count.saturating_add(1);
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
//  Tests — typestate transition correctness
// ═══════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    fn make_meta(prompt_len: usize) -> Arc<RequestMeta> {
        Arc::new(RequestMeta {
            id: RequestId::new_v4(),
            external_id: "test".into(),
            sequence_id: SequenceId(1),
            input_ids: (0..prompt_len as i32).collect(),
            max_tokens: 32,
            sampling: SamplingParams::default(),
            priority: Priority::default(),
            stream: false,
            stop_sequences: vec![],
            ignore_eos: false,
            diffusion: None,
            arrival_time: Instant::now(),
        })
    }

    #[test]
    fn queued_to_prefilling_transfers_meta() {
        let s = InferenceSession::<Queued>::new(make_meta(4), RequestHandle::noop());
        let s = s.start_prefill();
        assert_eq!(s.state.prompt_len, 4);
        assert_eq!(s.state.num_computed_tokens, 0);
        assert!(s.state.inflight.is_none());
    }

    #[test]
    fn prefilling_to_decoding_after_complete() {
        let s = InferenceSession::<Queued>::new(make_meta(4), RequestHandle::noop());
        let mut s = s.start_prefill();
        s.state.num_computed_tokens = 4;
        assert!(s.is_complete());
        let s = s.start_decode();
        assert_eq!(s.state.seq_position, 4);
        assert_eq!(s.state.prompt_len, 4);
    }

    #[test]
    fn decoding_to_finished_carries_output() {
        let q = InferenceSession::<Queued>::new(make_meta(2), RequestHandle::noop());
        let mut p = q.start_prefill();
        p.state.num_computed_tokens = 2;
        let mut d = p.start_decode();
        d.append_token(99);
        let f = d.finish(FinishReason::Eos);
        assert_eq!(f.state.output_tokens, vec![99]);
    }

    #[test]
    fn bump_preempted_increments_count() {
        let q = InferenceSession::<Queued>::new(make_meta(4), RequestHandle::noop());
        let mut p = q.start_prefill();
        p.state.num_computed_tokens = 4;
        let mut d = p.start_decode();
        assert_eq!(d.state.preemption_count, 0);
        d.bump_preempted();
        d.bump_preempted();
        assert_eq!(d.state.preemption_count, 2);
    }
}
